[package]
name = "preprocessor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ethereum
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "adf1a0b14cef90b9536f28ef89da1fab316465e1" }
halo2curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.3.1" }
sync-committee-prover = { git = "https://github.com/polytope-labs/sync-committee-rs", version = "0.1.0", features=["testnet"] }
sync-committee-primitives = { git = "https://github.com/polytope-labs/sync-committee-rs", version = "0.1.0", features=["testnet"] }

#crypto
group = "0.12"

# misc
hex = "0.4"
log = "=0.4.20"
eyre = "0.6"
tokio = { version = "1", features = ["full"]}
itertools = "0.11.0"
serde_json = "1.0.78"
serde = {version = "1.0.130", features = ["derive"] }
# local
eth-types = { path = "../eth-types" }
lightclient-circuits = { path = "../lightclient-circuits" }

[dev-dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02", features = [
    "dev-graph",
] }
halo2-base = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "community-edition", default-features = false, features = [
    "halo2-pse",
    "display",
] }
snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "community-edition", default-features = false, features = [
    "display",
    "loader_halo2",
    "loader_evm",
    "halo2-pse",
] }
ark-std = { version = "0.4.0", features = ["print-trace"] }
# sync-committee-verifier = { git = "https://github.com/polytope-labs/sync-committee-rs", version = "0.1.0", features=["testnet"] }
