[package]
name = "preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
ssz_rs.workspace = true
halo2curves.workspace = true
group.workspace = true
beacon-api-client.workspace = true

# misc
eyre = "0.6"
tokio = { version = "1", features = ["full"] }

hex.workspace = true
log.workspace = true
itertools.workspace = true
serde_json.workspace = true
serde.workspace = true
ethereum-consensus-types.workspace = true
sha2.workspace = true
# local
eth-types.workspace = true
lightclient-circuits.workspace = true
reqwest = "0.11.22"

[dev-dependencies]
halo2-base.workspace = true
snark-verifier-sdk.workspace = true
ark-std.workspace = true
