[package]
name = "spectre-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
# cli
clap = { version = "=4.2", features = ["derive"] }
strum = { version = "=0.25", features = ["derive"] }
cli-batteries = "=0.4"
eyre = "0.6"
anstyle = "=1.0.0"


# halo2
halo2curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.3.1" }

# verifier SDK 
snark-verifier = { git = "https://github.com/axiom-crypto/snark-verifier.git", tag = "v0.1.1", default-features = false, features = [
    "display",
    "loader_halo2",
    "loader_evm",
] }
snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", tag = "v0.1.1", default-features = false, features = [
    "display",
    "loader_halo2",
    "loader_evm",
] }
halo2_solidity_verifier = { git = "https://github.com/privacy-scaling-explorations/halo2-solidity-verifier", branch = "ac/initial-verifier-PR" }

# local
lightclient-circuits = { path = "../lightclient-circuits" }
preprocessor = { path = "../preprocessor" }
eth-types = { path = "../eth-types" }


# misc
url = "2"
itertools = "0.11.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.78"


# ethereum
ethers = { version = "2.0.7", default_features = false, features = [
    "ethers-solc",
    "abigen",
] }

[build-dependencies]
cli-batteries = "=0.4"
