[package]
name = "lightclient-circuits"
version = "0.1.0"
authors = ["timoftime <timofey@chainsafe.io>", "ec2 <eric@chainsafe.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# halo2
halo2_proofs.workspace = true
halo2curves.workspace = true
halo2-base.workspace = true
halo2-ecc.workspace = true
poseidon.workspace = true
# verifier SDK
snark-verifier.workspace = true
snark-verifier-sdk.workspace = true
# crypto
group.workspace = true
num-bigint = { version = "0.4", features = ["rand"] }
pasta_curves = "0.4.1"
ff = "0.12"
sha2 = { version = "0.10.6", features = ["compress"] }
# ethereum
sync-committee-primitives.workspace = true
ssz-rs.workspace = true

# local
eth-types = { path = "../eth-types" }

# misc
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.78"
array-init = "2.0.0"
strum = "0.25"
strum_macros = "0.25"
rand = "0.8"
itertools = "0.11.0"
lazy_static = "1.4"
log = "0.4"
hex = "0.4"
rayon = "1.7.0"
ark-std = { version = "0.4.0", features = ["print-trace"] }

poseidon_native = { git = "https://github.com/axiom-crypto/halo2.git", branch = "axiom/dev", package = "poseidon" }

[dev-dependencies]
rstest = "0.18.2"
test-utils = { git = "ssh://git@github.com/sygmaprotocol/Zipline.git", rev = "27e8a01" }
ethereum-consensus-types = { git = "ssh://git@github.com/sygmaprotocol/Zipline.git", rev = "27e8a01" }
light-client-verifier = { git = "ssh://git@github.com/sygmaprotocol/Zipline.git", rev = "27e8a01" }
ethers = "2.0.10"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
anyhow = "1.0.75"

[features]
default = []
