[profile.default]
src = 'contracts'
out = 'out'
ffi = true
libs = ['lib']
optimizer = true
optimizer_runs = 1_000_000_000
solc = "0.8.16"
fs_permissions = [{ access = "read", path = "./test/data/"}]

[profile.default.optimizer_details]
constantOptimizer = true 
yul = false 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
