[profile.default]
src = 'src'
out = 'out'
ffi = true
libs = ['lib']
optimizer = true
optimizer_runs = 1_000_000_000
solc = "0.8.19"
fs_permissions = [{ access = "read", path = "./test/data/"}]

[profile.default.optimizer_details]
constantOptimizer = true 
yul = false 

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
local = "${LOCAL_RPC_URL}"
