name: Spectre Deploy
on:
  push:
    branches:
    - devops

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: checkout contracts repo
      uses: actions/checkout@v4
      with:
        repository: ChainSafe/spectre-contracts
        path: contracts

    - name: checkout foundry
      uses: actions/checkout@v4
      with:
        repository: foundry-rs/forge-std
        path: contracts/lib/forge-std

    - name: deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude '.git'
        path: ./
        remote_path: /home/ubuntu/Spectre
        remote_host: ${{ secrets.ACTIONS_HOST }}
        remote_user: ${{ secrets.ACTIONS_USER }}
        remote_key: ${{ secrets.ACTIONS_CONNECTIONS }}

    - name: slack notify
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,job,eventName,ref,workflow # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always()